### PR TITLE
README region information

### PR DESCRIPTION
**Pull request by pnlrogue1**
Adds `-region <region code>` to the examples for calling the application.

Adds a table listing the regions. These regions are pulled directly out of the code so if they're incorrect/incomplete the code needs an update, too!

### CODE REVIEW

**Comment by pnlrogue1** [comment]
Not sure why this should fail on a Go test - I'm not touching the code, only the README file!

**Comment by andig** [comment]
Because the linter wanted to run and somehow wasn't installed successfully.

**Review by joeshaw — CHANGES_REQUESTED** [review]
👍 thank you!

**Comment by pnlrogue1** [comment]
Very happy to help with a great project! Wish I could contribute to the code itself rather than just the README but Go is outside my skillset, sadly

**Comment by joeshaw** [comment]
No worries, any contribution is helpful.

I've mentioned this elsewhere (and should probably update the README for it) but I'm no longer able to use this tool anymore.  I'm in the US and a while back Nissan eliminated the API this uses for North American users and replaced it another one (that's joeshaw/leaf, but that's now also broken by Nissan).

So I rely on folks who can still use it to help me out here (and @andig has been particularly helpful in this regard).

**Pull request merged**
